using System.Runtime.InteropServices;
using System.Xml.Linq;
using OneNoteInterop = Microsoft.Office.Interop.OneNote;

namespace QuickOneNote;

/// <summary>A OneNote section the user can target.</summary>
public sealed record SectionInfo(string Id, string DisplayPath);

/// <summary>
/// Talks to the locally installed desktop OneNote through its COM automation API using
/// strongly-typed early binding (interop generated by tlbimp; see the .csproj). Enumerates
/// sections, ensures a target page exists, and appends text/images to it.
/// </summary>
public sealed class OneNoteClient : IOneNoteBackend
{
    private static readonly XNamespace One = "http://schemas.microsoft.com/office/onenote/2013/onenote";

    // A DATE the marshaler accepts (VT_DATE 0 == 1899-12-30). We always pass force:true so the
    // "expected last modified" value is not actually used for conflict detection.
    private static readonly DateTime NoExpectedDate = DateTime.FromOADate(0);

    private static OneNoteInterop.Application CreateApp()
    {
        try
        {
            return new OneNoteInterop.Application();
        }
        catch (COMException ex)
        {
            throw new InvalidOperationException(
                "Could not start desktop OneNote automation. Make sure the desktop OneNote is installed. " +
                "Details: " + ex.Message, ex);
        }
    }

    /// <summary>Return every section in every open notebook, flattened to "Notebook / Group / Section".</summary>
    public List<SectionInfo> GetSections()
    {
        var app = CreateApp();
        try
        {
            app.GetHierarchy(null, OneNoteInterop.HierarchyScope.hsSections, out string xml,
                OneNoteInterop.XMLSchema.xs2013);

            var doc = XDocument.Parse(xml);
            var sections = new List<SectionInfo>();
            foreach (var notebook in doc.Descendants(One + "Notebook"))
            {
                string nbName = (string?)notebook.Attribute("name") ?? "Notebook";
                CollectSections(notebook, nbName, sections);
            }
            return sections;
        }
        finally
        {
            Release(app);
        }
    }

    private static void CollectSections(XElement parent, string pathSoFar, List<SectionInfo> into)
    {
        foreach (var child in parent.Elements())
        {
            if (child.Name == One + "Section")
            {
                string? id = (string?)child.Attribute("ID");
                string name = (string?)child.Attribute("name") ?? "Section";
                bool inRecycleBin = ((string?)child.Attribute("isInRecycleBin")) == "true";
                if (!string.IsNullOrEmpty(id) && !inRecycleBin)
                    into.Add(new SectionInfo(id, $"{pathSoFar} / {name}"));
            }
            else if (child.Name == One + "SectionGroup")
            {
                bool inRecycleBin = ((string?)child.Attribute("isRecycleBin")) == "true";
                if (inRecycleBin) continue;
                string groupName = (string?)child.Attribute("name") ?? "Group";
                CollectSections(child, $"{pathSoFar} / {groupName}", into);
            }
        }
    }

    /// <summary>Append captured content to OneNote according to the chosen mode.</summary>
    public void Append(AppSettings settings, CapturedContent content)
    {
        if (string.IsNullOrEmpty(settings.SectionId))
            throw new InvalidOperationException("No OneNote section is selected. Open Settings first.");
        if (content.IsEmpty)
            throw new InvalidOperationException("Nothing was captured.");

        var app = CreateApp();
        try
        {
            string pageId = settings.Mode == CaptureMode.TodaysPage
                ? EnsureTodaysPage(app, settings.SectionId)
                : CreateFreshPage(app, settings.SectionId);

            var blocks = BuildContentBlocks(content, includeTimestamp: settings.Mode == CaptureMode.TodaysPage);
            AppendBlocksToPage(app, pageId, blocks);

            // Intentionally do NOT call NavigateTo — that would pull OneNote to the foreground.
            // Notes are added silently in the background.
        }
        finally
        {
            Release(app);
        }
    }

    /// <summary>Append a titled series of screenshots (title bold, caption above each image).</summary>
    public void AppendSeries(AppSettings settings, string title, IReadOnlyList<SeriesItem> items)
    {
        if (string.IsNullOrEmpty(settings.SectionId))
            throw new InvalidOperationException("No OneNote section is selected. Open Settings first.");
        if (items.Count == 0)
            throw new InvalidOperationException("The series is empty.");

        var app = CreateApp();
        try
        {
            string pageId = settings.Mode == CaptureMode.TodaysPage
                ? EnsureTodaysPage(app, settings.SectionId)
                : CreateFreshPage(app, settings.SectionId);

            var blocks = new List<XElement>();
            if (!string.IsNullOrWhiteSpace(title))
            {
                // A divider line + a bold title mark the start of a new section.
                blocks.Add(new XElement(One + "OE",
                    new XElement(One + "T", new XCData("<span style='color:#BFC4CC'>" + new string('─', 42) + "</span>"))));
                blocks.Add(new XElement(One + "OE",
                    new XElement(One + "T", new XCData("<span style='font-weight:bold'>" + Html(title) + "</span>"))));
            }

            foreach (var item in items)
            {
                // Separate the title/previous screenshot from this one with a blank line.
                if (blocks.Count > 0) blocks.Add(BlankLine());

                if (!string.IsNullOrWhiteSpace(item.Caption))
                    foreach (var line in item.Caption!.Replace("\r\n", "\n").Split('\n'))
                        blocks.Add(new XElement(One + "OE", new XElement(One + "T", new XCData(Html(line)))));

                if (item.Png is { Length: > 0 })
                    blocks.Add(new XElement(One + "OE",
                        new XElement(One + "Image",
                            new XAttribute("format", "png"),
                            new XElement(One + "Data", Convert.ToBase64String(item.Png)))));
            }

            AppendBlocksToPage(app, pageId, blocks);
        }
        finally
        {
            Release(app);
        }
    }

    // ----- Page resolution -----

    private string CreateFreshPage(OneNoteInterop.Application app, string sectionId)
    {
        app.CreateNewPage(sectionId, out string pageId, OneNoteInterop.NewPageStyle.npsBlankPageWithTitle);
        SetPageTitle(app, pageId, "Quick note — " + DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
        return pageId;
    }

    private string EnsureTodaysPage(OneNoteInterop.Application app, string sectionId)
    {
        string title = DateTime.Now.ToString("yyyy-MM-dd");

        app.GetHierarchy(sectionId, OneNoteInterop.HierarchyScope.hsPages, out string xml,
            OneNoteInterop.XMLSchema.xs2013);
        var doc = XDocument.Parse(xml);
        var existing = doc.Descendants(One + "Page")
            .FirstOrDefault(p => string.Equals((string?)p.Attribute("name"), title, StringComparison.Ordinal));
        if (existing != null)
            return (string)existing.Attribute("ID")!;

        app.CreateNewPage(sectionId, out string pageId, OneNoteInterop.NewPageStyle.npsBlankPageWithTitle);
        SetPageTitle(app, pageId, title);
        return pageId;
    }

    private void SetPageTitle(OneNoteInterop.Application app, string pageId, string title)
    {
        string pageXml =
            $"<one:Page xmlns:one=\"{One}\" ID=\"{pageId}\">" +
            "<one:Title><one:OE><one:T><![CDATA[" + Escape(title) + "]]></one:T></one:OE></one:Title>" +
            "</one:Page>";
        app.UpdatePageContent(pageXml, NoExpectedDate, OneNoteInterop.XMLSchema.xs2013, true);
    }

    // ----- Content building & appending -----

    private List<XElement> BuildContentBlocks(CapturedContent content, bool includeTimestamp)
    {
        var blocks = new List<XElement>();

        // In today's-page mode we prefix a "[HH:mm] " stamp inline on the first line so each
        // capture is distinguishable without adding a separate line.
        string prefix = includeTimestamp ? $"[{DateTime.Now:HH:mm}] " : "";
        bool hasText = !string.IsNullOrWhiteSpace(content.Text);

        if (hasText)
        {
            var lines = content.Text!.Replace("\r\n", "\n").Split('\n');
            for (int i = 0; i < lines.Length; i++)
            {
                string text = (i == 0 ? prefix : "") + lines[i];
                blocks.Add(new XElement(One + "OE", new XElement(One + "T", new XCData(text))));
            }
        }

        if (content.PngImage is { Length: > 0 })
        {
            // An image can't share a line with text, so an image-only capture gets a small
            // stamp line of its own (when timestamps are on).
            if (!hasText && includeTimestamp)
                blocks.Add(new XElement(One + "OE", new XElement(One + "T", new XCData(prefix.TrimEnd()))));

            string base64 = Convert.ToBase64String(content.PngImage);
            blocks.Add(new XElement(One + "OE",
                new XElement(One + "Image",
                    new XAttribute("format", "png"),
                    new XElement(One + "Data", base64))));
        }

        return blocks;
    }

    private void AppendBlocksToPage(OneNoteInterop.Application app, string pageId, List<XElement> blocks)
    {
        if (blocks.Count == 0) return;

        app.GetPageContent(pageId, out string xml, OneNoteInterop.PageInfo.piBasic,
            OneNoteInterop.XMLSchema.xs2013);
        var doc = XDocument.Parse(xml);
        var page = doc.Root!;

        var outline = page.Elements(One + "Outline").FirstOrDefault();
        if (outline == null)
        {
            outline = new XElement(One + "Outline", new XElement(One + "OEChildren"));
            page.Add(outline);
        }

        var oeChildren = outline.Element(One + "OEChildren");
        if (oeChildren == null)
        {
            oeChildren = new XElement(One + "OEChildren");
            outline.Add(oeChildren);
        }

        // If the page already has content, add a blank line so this new note is set apart.
        if (oeChildren.Elements().Any())
            oeChildren.Add(BlankLine());

        foreach (var block in blocks)
            oeChildren.Add(block);

        app.UpdatePageContent(doc.ToString(), NoExpectedDate, OneNoteInterop.XMLSchema.xs2013, true);
    }

    // ----- Helpers -----

    private static string Escape(string s) => s.Replace("]]>", "]]]]><![CDATA[>");

    private static string Html(string s) => System.Net.WebUtility.HtmlEncode(s);

    /// <summary>A small blank line used to separate entries on a page.</summary>
    private XElement BlankLine() => new(One + "OE",
        new XElement(One + "T", new XCData("<span style='font-size:6.0pt'>&#160;</span>")));

    private static void Release(object? o)
    {
        if (o != null && Marshal.IsComObject(o))
        {
            try { Marshal.ReleaseComObject(o); } catch { /* ignore */ }
        }
    }
}
